name: OddItem
main: info.somethingodd.bukkit.OddItem.OddItemBase
version: 0.8.1
website: http://bukkit.somethingodd.info
author: petteyg359
description: Item database stuff.
commands:
    odditem:
        aliases: oi
        usage:  |
                /<command> [search item]|[info]|[list]|[reload]
                search - Lists aliases for item
                info - Shows number of items loaded.
permissions:
    odditem:
        children:
            odditem.alias: true
            odditem.info: true
            odditem.reload: true
        default: op
    odditem.alias:
        default: true
    odditem.info:
        default: true
    odditem.reload:
        default: op
